blog/urls.py
from django.urls import path, include
from . import views
app_name = 'blog'

urlpatterns = [
    path("test1/", views.test1),
    path("test2/<int:id>/", views.test2),
    path("test3/<year>/<mon>/<day>/", views.test3),
    path("", views.list, name='list'),
    path("<int:id>/", views.detail, name='detail'),
    path("test4/", views.test4),
    path("profile/", views.profile),
    path("tag/<id>", views.tag_list),
    path("test7/", views.test7),
    path("new/", views.post_create, name='create'),
    path("update/<id>", views.post_update, name='update'),
    path("delete/<id>", views.post_delete, name='delete'),

]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static 

urlpatterns = [
    path("admin/", admin.site.urls),
    path("blog/", include("blog.urls")),
    path("book/", include("book.urls")),
    path("gallery/", include('gallery.urls')),
    path('accounts/', include('accounts.urls')),

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=250)
    body = models.TextField()
    tag = models.ManyToManyField('Tag', blank=True)
    ip = models.GenericIPAddressField(null=True)
    
    def __str__(self): #admin 페이지에 이름 표시
        return self.title
    
    def get_absolute_url(self):
        return reverse('blog:detail', args=[self.id])
    
class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    author = models.CharField(max_length=20)
    message = models.TextField()
    created = models.DateField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    deleted = models.BooleanField(default=False)

class User(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone_number = models.CharField(max_length=20)
    address = models.CharField(max_length=50)
    
class Tag(models.Model):
    name = models.CharField(max_length=50, unique=True)
    
    def __str__(self):
        return self.name

blog/forms.py
from django import forms
from .models import Post

class PostForm(forms.Form):
    title= forms.CharField(label='제목')
    body= forms.CharField(label='내용', widget=forms.Textarea)
    
class PostModelForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'body']
        

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, Http404
from .models import *
from django.utils import timezone
from .forms import PostModelForm

def test1(request):
    #서비스 구현
    return HttpResponse('test1!')

def test2(request, id):
    print("타입 :",type(id))
    return HttpResponse(id)

def test3(request, year, mon, day):
    return HttpResponse(f'{year}년 {mon}월 {day}일')

# def list(request):
#     post_list = Post.objects.all()
#     titles = ''
#     for post in post_list:
#         titles += post.title
#     return HttpResponse(titles)


def list(request):
    post_list = Post.objects.all()
    search_key = request.GET.get("keyword")
    if search_key:
        post_list = Post.objects.filter(title__icontains=search_key)
    return render(request, 'blog/list.html', {'post_all':post_list, 'q':search_key})

def detail(request, id):
    post = get_object_or_404(Post, id=id)
    comment_list = post.comments.all()
    tag_list = post.tag.all()
    
    return render(request, "blog/detail.html", {'post':post, 'comment_all': comment_list, 'tag_list':tag_list})

def test4(request):
    d1 = timezone.now()
    var = """
    Miracles happen to only those who believe in them.
    Think like a man of action and act like man of thought.
    Courage is very important. Like a muscle, it is strengthened by use.
    Life is the art of drawing sufficient conclusions from insufficient premises.
    By doubting we come at the truth.
    A man that has no virtue in himself, ever envies virtue in others.
    When money speaks, the truth keeps silent.
    Better the last smile than the first laughter.
    """

    return render(request, 'blog/test4.html', {'score': 95, 'var':var, 'd1': d1})

def profile(request):
    user = User.objects.first()
    return render(request, 'blog/profile.html', {'user':user})

def tag_list(request, id):
    tag = Tag.objects.get(id=id)
    post_list = tag.post_set.all()
    return render(request, 'blog/list.html', {'post_all':post_list})

def test7(request):
    print('요청 방식 :', request.method)
    print('Get 방식으로 전달된 QueryString :', request.GET)
    print('Post방식으로 전달된 QueryString :', request.POST)
    print('업로드된 파일 :', request.FILES)
    return render(request, 'blog/form_test.html')

def post_create(request):
    if request.method == 'POST':
        form = PostModelForm(request.POST)
        if form.is_valid():
            print('======>',form.cleaned_data)
            # post = Post.objects.create(**form.cleaned_data)
            post = form.save(commit=False)
            post.ip = request.META['REMOTE_ADDR']
            post.save()
            return redirect(post)
    else:
        form = PostModelForm()
        return render(request, 'blog/post_form.html', {'form':form})
    
    
def post_update(request, id):
    post = get_object_or_404(Post, id=id)
    if request.method == 'POST':
        form = PostModelForm(request.POST, instance=post)
        if form.is_valid():
            form.save()
            return redirect('blog:list')
    else:
        form = PostModelForm(instance=post)
        return render(request, 'blog/post_update.html', {'form':form})
    
def post_delete(request, id):
    post=get_object_or_404(Post, id=id)
    if request.method == 'POST':
        post.delete()
        return redirect('blog:list')
    else:
        return render(request, 'blog/post_delete.html', {'post':post}) 
    
    

blog/templates/blog/detail.html
{% extends "layout.html" %}
{% block title %}
    Post 상세보기
{% endblock  %}
{% block content %}
    <h1> {{post.title}} </h1>

    제목 : {{post.title}}<br>
    내용 : {{post.body}}<br>
    
    <hr>
    <p>댓글</p>

    {% for comment in comment_all %}
        <P>{{comment.message}} / {{comment.author}} /  {{comment.updated}}</p>
    {% empty %}
        댓글이 존재하지 않습니다.
    {% endfor %}

    <hr>
    <p>태그</p>
    {% for tag in tag_list %}
        #<a href ='/blog/tag/{{tag.id}}'>{{tag.name}}</a>

    {% endfor %}

    <hr>
    <a href="{% url 'blog:list' %}">[목록보기]</a>
    <a href="{% url 'blog:update' post.id %}">[글 수정]</a>
    <a href="{% url 'blog:delete' post.id %}">[글 삭제]</a>
{% endblock  %}

blog/templates/blog/form_test.html
{% extends "layout.html" %}
{% block title %} Form Test {% endblock %}
{% block content %}
    <form action="" method="POST", enctype='multipart/form-data'>
        {% csrf_token %}

        아이디 : <input type="text" name="id" value="user1"><br>
        비밀번호 : <input type="password" name="pwd" value="12345"><br>
        사진 : <input type='file' name='pic'><br>
        
        성별 :     
        <input type="radio" name="gender" value="male" checked > 남자
        <input type="radio" name="gender" value="female"> 여자 <br>
        
        관심분야:
        <input type="checkbox" name="interest" value="AI" checked >인공지능 
        <input type="checkbox" name="interest" value="BD">빅데이터 
        <input type="checkbox" name="interest" value="DA" checked >데이터 분석 <br>

        연령대:
        <select name="age">
            <option value="2">20대</option>
            <option value="3">30대</option>
            <option value="4" selected >40대</option>         
        </select><br>

        참고 사항: <br>
        <textarea cols="30" rows="10" name="remark">통계학 전공</textarea><br>
        <input type="submit" value="확인">
    </form>
{% endblock %}

blog/templates/blog/list.html
{% extends "layout.html" %}

{% block title %}
    Post 목록
{% endblock title %}

{% block content %}
<h1>Post 목록 보기</h1>

    <form action="" method="get">
        {% csrf_token %}
        검색어:<input type="text" name="keyword" value="{{q|default:''}}" >
        <input type="submit" value="검색">
    </form> 
       

    {% for post in post_all %}
        <a href="{% url 'blog:detail' post.id  %}"> {{post.title}} </a><br>
    {% endfor %}    

    <a href="{% url 'blog:create'  %}">[새 글 쓰기]</a>

{% endblock content %}

blog/templates/blog/post_delete.html
{% extends "layout.html" %}
{% block title %}Post 삭제{% endblock %}
{% block content %}
    <h1> POST 삭제</h1>
    {{post}}  글을 정말로 삭제하시겠습니까?

    <form action="" method="POST">
        {% csrf_token %}
        <input type="submit" value="네, 삭제합니다">
    </form>

    <a href="{% url 'blog:list'%}">아니오, 취소합니다</a>
    
{% endblock %}

blog/templates/blog/post_form.html
{% extends "layout.html" %}
{% block title %} Post 등록 {% endblock %}
{% block content %}
    <h1> POST 등록</h1>
    <form action="" method="POST">
        {% csrf_token %}
        <table>
            {{form.as_table}}
        </table>
        <input type="submit" value="등록">
    </form>
{% endblock %}

blog/templates/blog/post_update.html
{% extends "layout.html" %}

{% block title %}Post 수정{% endblock %}

{% block content %}
    <h1> POST 수정</h1>

    <form action="" method="POST">
        {% csrf_token %}
        <table>
            {{form.as_table}}
        </table>
        <input type="submit" value="수정">
    </form>
{% endblock %}

blog/templates/blog/profile.html
{% extends "layout.html" %}
{% block title %}
    Profile
{% endblock %}
{% block content %}
    <h1>{{user.name}}'s profile </h1>

    <ul>
        <li>이름 : {{user.name}}</li>
        <li>전화번호 : {{user.profile.phone_number}}</li>
        <li>주소 : {{user.profile.address}}</li>
    </ul>
        

{% endblock %}

blog/templates/blog/test4.html
{% if score >= 60 %}
    합격!
{% else %}
    불합격!
{% endif %}

<hr>

{{var|linebreaks}}
<hr>
{{var|truncatechars:100}}
<hr>
{{var|truncatewords:50}}

<hr>
{{d1}}<br>
{{d1|date:'Y-m-d'}}<br>
{{d1|time:'P'}}<br>